version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  web_stat:
    tty: true
    stdin_open: true
    container_name: web_stat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/docker:cached
    working_dir: /var/www/docker
    command: bash
    networks:
      - app-tier